### PR TITLE
Agdroid 409

### PR DESCRIPTION
**Pull request by secondsun**
## Required software:
* Android SDK installed in maven
* Emulator or device attached to computer
* aerogear-android-core 2.2-SNAPSHOT
* aerogear-android-security 2.2-SNAPSHOT
 
## How to test:
* mvn clean install

## Expected results
* 75 passing tests

### CODE REVIEW

**Comment by secondsun** [comment]
@danielpassos @abstractj Care to take a look?

I'm open to suggestions for changing this.  using a LIKE instead of an = makes me feel icky and I would like feedback for making me feel less icky.

**Comment by danielpassos** [comment]
:eyes:

**Comment by danielpassos** [comment]
:+1: 

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] AeroGear Android Store Parent ..................... SUCCESS [3.035s]
[INFO] AeroGear Android Store Library .................... SUCCESS [10.169s]
[INFO] AeroGear Android Store Test ....................... SUCCESS [3:57.035s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4:16.445s
[INFO] Finished at: Tue Apr 07 16:21:32 BRT 2015
[INFO] Final Memory: 48M/172M
[INFO] ------------------------------------------------------------------------
```

**Comment by abstractj** [comment]
@secondsun landed

**Pull request merged**
